language: clojure
sudo: required
lein: 2.7.1
jdk:
  - openjdk7
  - oraclejdk8
before_install:
  - sudo chmod +x ./travis/*
  - sudo ./travis/bootstrap.sh
  - sudo ./travis/download_kafka.sh
  - sudo ./travis/run_kafka.sh
  - sleep 20 # make sure kafka and zk have started
  - sudo ./travis/create_test_kafka_topic.sh

script: travis_retry env JAVA_HOME=/usr/lib/jvm/java-8-oracle/bin/java lein test

notifications:
  email:
    on_success: change # default: change
    on_failure: change # default: always
